### ISSUE TITLE
Update requirements.txt file

### ISSUE THREAD

**Issue by AJ-54** [AJ-54/e-learning#22]
I want a user to create a virtualenv and clone this project and then notify me about the exact packages required. I while making this project didn't create a virtualenv so pip freeze displayed all the global modules.

**Comment by hp77-creator** [comment]
I can try but there is an issue 'could not find a version that satisfies the requirement' while performing command 'pip install requirements.txt'

**Comment by AJ-54** [comment]
Great Work @hp77-creator. This issue is closed with your PR.
